package com.example.meterreadingsapp.api

import okhttp3.MultipartBody
import okhttp3.RequestBody
import retrofit2.Response
import retrofit2.http.Header
import retrofit2.http.Multipart
import retrofit2.http.POST
import retrofit2.http.Part
import retrofit2.http.Url

/**
 * Retrofit interface for interacting with your S3 Storage API for document uploads.
 * Assumes a pre-signed URL POST endpoint for direct file uploads.
 */
interface StorageApiService {

    /**
     * Uploads a file (image) to a pre-signed S3 URL using a multipart POST request.
     * This method is designed for direct uploads to S3 where the server provides a pre-signed URL.
     *
     * @param url The full pre-signed URL generated by your backend/Supabase Storage.
     * @param contentType The Content-Type header for the file (e.g., "image/jpeg", "image/png").
     * @param contentLength The Content-Length header for the file size.
     * @param body The MultipartBody.Part containing the file data (e.g., image).
     * @return A Retrofit Response object with Unit type, indicating success (e.g., 200 OK or 204 No Content).
     */
    @Multipart
    @POST
    suspend fun uploadFileToS3(
        @Url url: String, // The full pre-signed URL provided by your backend
        @Header("Content-Type") contentType: String,
        @Header("Content-Length") contentLength: Long,
        @Part body: MultipartBody.Part // The file content
    ): Response<Unit>

    // If your S3 API requires specific headers like X-Amz-Date, X-Amz-Signature etc.,
    // those would typically be part of the pre-signed URL itself or handled by an interceptor.
    // For direct upload to a pre-signed URL, usually Content-Type and Content-Length are sufficient as headers.
}
