package com.example.meterreadingsapp.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Data class representing an API request that needs to be queued and sent later.
 * This entity will be stored in the Room database when the app is offline.
 *
 * @param id Unique identifier for the queued request. Auto-generated by Room.
 * @param endpoint The API endpoint (e.g., "readings").
 * @param method The HTTP method (e.g., "POST").
 * @param body The JSON string representation of the request body (e.g., a serialized Reading object).
 * @param timestamp The time the request was queued, for ordering or aging out.
 * @param attemptCount The number of times this request has been attempted.
 */
@Entity(tableName = "queued_requests")
data class QueuedRequest(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0, // Auto-generated primary key for Room
    val endpoint: String,
    val method: String,
    val body: String, // Store the request body as a JSON string
    val timestamp: Long = System.currentTimeMillis(),
    var attemptCount: Int = 0
)
