package com.example.meterreadingsapp.data

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.google.gson.annotations.SerializedName

/**
 * Data class representing a 'reading' for a meter.
 * Corresponds to the 'readings' table in your Supabase database.
 * This class will also serve as the request body for POSTing new readings.
 *
 * @param id Unique identifier for the reading. Uses UUID format. Auto-generated by DB.
 * @param meter_id Foreign key linking to the 'meters' table.
 * @param value The actual meter reading value (String because of 'character varying' type in schema).
 * @param date The date of the reading (String for date).
 * @param consumption Calculated consumption (nullable).
 * @param generation Calculated generation (nullable).
 * @param is_valid Indicates if the reading is valid (default true).
 * @param validation_message Any validation message (nullable).
 * @param created_by UUID of the user who created this reading (nullable).
 * @param created_at Timestamp when the record was created.
 * @param value_2 Secondary reading value (nullable).
 * @param is_auto_generated Flag if reading was auto-generated (default false).
 * @param notes Any notes for the reading (nullable).
 * @param read_by Name of the person who read the meter (nullable).
 * @param source_type Type of source for the reading (e.g., "manual", "automatic").
 * @param source_metadata Metadata related to the source (represented as a Map, nullable).
 * @param validation_status Status of the reading's validation (e.g., "valid", "invalid").
 * @param validation_messages List of validation messages (nullable).
 */
@Entity(tableName = "readings")
data class Reading(
    @PrimaryKey
    @SerializedName("id") val id: String, // UUID from Supabase
    @SerializedName("meter_id") val meter_id: String, // FIX: Changed back to non-nullable String as per DB schema
    @SerializedName("value") val value: String, // Value as String as per schema, convert to Double for calculations
    @SerializedName("date") val date: String, // Date as String as per schema
    @SerializedName("consumption") val consumption: String? = null,
    @SerializedName("generation") val generation: String? = null,
    @SerializedName("is_valid") val is_valid: Boolean = true,
    @SerializedName("validation_message") val validation_message: String? = null,
    @SerializedName("created_by") val created_by: String? = null, // UUID of user who created
    @SerializedName("created_at") var created_at: String? = null, // This is server-populated, so nullable 'var' is correct
    @SerializedName("value_2") val value_2: String? = null,
    @SerializedName("is_auto_generated") val is_auto_generated: Boolean = false,
    @SerializedName("notes") val notes: String? = null,
    @SerializedName("read_by") val read_by: String? = null,
    @SerializedName("source_type") val source_type: String? = null,
    @SerializedName("source_metadata") val source_metadata: Map<String, Any?>? = null, // Stays Map<String, Any?>
    @SerializedName("validation_status") val validation_status: String? = null,
    @SerializedName("validation_messages") val validation_messages: List<String>? = null
)
